version: "3.9"
services:
  octant-web:
    platform: linux/amd64
    #build: .
    image: octant:latest
    
    ports:
      - "8080:80"
    volumes:
      - type: bind
        read_only: true
        source: ~/.kube
        target: /home/octant/.kube
      - type: bind
        read_only: true
        source: ~/.aws
        target: /home/octant/.aws
